name: Genisys FRPC
slug: genisys-frpc          # usa lo stesso nome della cartella dell'add-on
version: "0.4.2"            # alza sempre la versione quando modifichi
description: Espone Home Assistant tramite FRP (reverse proxy) usando un token condiviso.
url: https://github.com/genisysdomotica-ux/genisys-ha-addons

arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386

init: false
startup: services
ingress: false
panel_icon: mdi:cloud-lock-outline

options:
  frp_server_addr: api.genisysdomotica.it
  frp_server_port: 7000
  frp_shared_token: ""
  local_ip: homeassistant
  local_port: 8123
  subdomain: ""
  custom_domain: ""

schema:
  frp_server_addr: str
  frp_server_port: int
  frp_shared_token: password
  local_ip: str
  local_port: int
  subdomain: str?
  custom_domain: str?
